export const LiquidityActionTypes = {
  FETCH_USER_LIQUIDITY_PENDING: 'FETCH_USER_LIQUIDITY_PENDING',
  FETCH_USER_LIQUIDITY_SUCCESS: 'FETCH_USER_LIQUIDITY_SUCCESS',
  FETCH_USER_LIQUIDITY_FAILURE: 'FETCH_USER_LIQUIDITY_FAILURE',
}

export const TokensActionTypes = {
  FETCH_TOKENS_PENDING: 'FETCH_TOKENS_PENDING',
  FETCH_TOKENS_SUCCESS: 'FETCH_TOKENS_SUCCESS',
  FETCH_TOKENS_FAILURE: 'FETCH_TOKENS_FAILURE',
  ADD_CUSTOM_TOKEN: 'ADD_CUSTOM_TOKEN',
  UPDATE_LIST_TOKEN: 'UPDATE_LIST_TOKEN',
}

export const WalletActionTypes = {
  CONNECT_WALLET_PROCESS_START: 'CONNECT_WALLET_PROCESS_START',
  CONNECT_WALLET_PROCESS_END: 'CONNECT_WALLET_PROCESS_END',
  CONNECT_WALLET_PENDING: 'CONNECT_WALLET_PENDING',
  CONNECT_WALLET_SUCCESS: 'CONNECT_WALLET_SUCCESS',
  CONNECT_WALLET_FAILURE: 'CONNECT_WALLET_FAILURE',
  RESET_WALLET_STATE: 'RESET_WALLET_STATE',
}

export const AdminActionTypes = {
  FETCH_ALL_LIQUIDITY: 'FETCH_ALL_LIQUIDITY',
  FETCH_CONTRACT_PARAMS: 'FETCH_CONTRACT_PARAMS',
}

export const BridgeActionTypes = {
  UPDATE_BRIDGE_INFO: 'UPDATE_BRIDGE_INFO',
}

export const DiamondHandActionTypes = {
  SET_DIAMOND_DATA: 'SET_DIAMOND_DATA',
  SET_DIAMOND_FILTER: 'SET_DIAMOND_FILTER',
  SET_DIAMOND_LIST: 'SET_DIAMOND_LIST',
  WATCH_DIAMOND_DATA: 'WATCH_DIAMOND_DATA',
  WATCH_DIAMOND_FILTER: 'WATCH_DIAMOND_FILTER',
  WATCH_DIAMOND_LIST: 'WATCH_DIAMOND_LIST',
}

export const listDiamond = [
  {
    id: 0,
    months: 1,
    percent: 2,
    value: false
  },{
    id: 1,
    months: 3,
    percent: 10,
    value: false
  },
  {
    id: 2,
    months: 6,
    percent: 30,
    value: false
  },
  {
    id: 3,
    months: 12,
    percent: 60,
    value: false
  },
];


